/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subnetting1;

import javax.swing.JOptionPane;

/**
 *
 * @author moerle
 */
public class FensterNetzGrenzen extends javax.swing.JFrame {

    /**
     * Creates new form FensterNetzGrenzen
     */
    
    Ipv4Wert adr1;
    public FensterNetzGrenzen() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adr1 = new Ipv4Wert();
        this.newAdr();
    }
    
    public FensterNetzGrenzen(Ipv4Wert adr1) {
        initComponents();
        this.adr1 = adr1;
        this.newAdr(adr1);
    }
    
    
    
    private void newAdr(Ipv4Wert adr1) {
        this.lblAdresse.setText(adr1.getAdresse());
        this.lblMaske.setText(adr1.getMaskeStr());
        this.lblErgebnis.setText("");
        this.fld1adr.setText("");
        this.fldLadr.setText("");
        this.fldBC.setText("");
        this.fldNID.setText("");    
        this.pack();
        this.setLocationRelativeTo(null);
    }
    private void newAdr() {
        adr1.setzeRNDAdress();
        this.lblAdresse.setText(adr1.getAdresse());
        this.lblMaske.setText(adr1.getMaskeStr());
        this.lblErgebnis.setText("");
        this.fld1adr.setText("");
        this.fldLadr.setText("");
        this.fldBC.setText("");
        this.fldNID.setText("");
        this.pack();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMaske = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        fldNID = new javax.swing.JTextField();
        fld1adr = new javax.swing.JTextField();
        fldBC = new javax.swing.JTextField();
        fldLadr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblErgebnis = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuEingabeIp = new javax.swing.JMenuItem();
        jMenuLongtoIp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Maske");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Netz ID");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Broadcast");

        lblMaske.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblMaske.setText("Maske");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("1. Adresse");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("L. Adresse");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Adresse");

        lblAdresse.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblAdresse.setText("Adresse");

        fldNID.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fldNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNIDActionPerformed(evt);
            }
        });

        fld1adr.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fld1adr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld1adrActionPerformed(evt);
            }
        });

        fldBC.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fldBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldBCActionPerformed(evt);
            }
        });

        fldLadr.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fldLadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldLadrActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Neu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newClick(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton2.setText("Überprüfen");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickAuswertung(evt);
            }
        });

        lblErgebnis.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblErgebnis.setText("Ergebnis");

        jMenu2.setText("IP");

        jMenuEingabeIp.setText("IP Eingeben");
        jMenuEingabeIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEingabeIpActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEingabeIp);

        jMenuLongtoIp.setText("Long --> IP");
        jMenuLongtoIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLongtoIpActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuLongtoIp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaske, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldNID)
                    .addComponent(fld1adr, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(fldBC, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(fldLadr, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(lblErgebnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblMaske, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldNID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldBC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld1adr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldLadr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErgebnis)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNIDActionPerformed

    private void fld1adrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld1adrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld1adrActionPerformed

    private void fldBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldBCActionPerformed

    private void fldLadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldLadrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldLadrActionPerformed

    private void newClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClick
        // TODO add your handling code here:
        this.newAdr();
    }//GEN-LAST:event_newClick

    private void onClickAuswertung(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickAuswertung
        // TODO add your handling code here:
        boolean richtig = true;
        String antwort="";
        long bcEing=Ipv4Wert.getStrtoLong(this.fldBC.getText());
        long nidEing=Ipv4Wert.getStrtoLong(this.fldNID.getText());
        long nr1Eing=Ipv4Wert.getStrtoLong(this.fld1adr.getText());
        long ladrEing=Ipv4Wert.getStrtoLong(this.fldLadr.getText());
        long bcSys = Ipv4Wert.getArrayToLong(adr1.getBCArray());
        long nidSys = Ipv4Wert.getArrayToLong(adr1.getNIDArray());
        if (nidEing != nidSys) {
            antwort += "NID falsch! ";
            richtig = false;
            adr1.addMsg("NID! Korrekt: "+nidSys+" Eingabe: "+nidEing);
        }
        if (bcEing!=bcSys) {
            antwort="BC falsch! ";
            richtig=false;
            adr1.addMsg("BC! Korrekt: "+bcSys+" Eingabe: "+bcEing);
        }
        if (nr1Eing != nidSys+1) {
            antwort += "1. Adresse falsch! ";
            richtig = false;
            adr1.addMsg("1. Adresse! Korrekt: "+(nidSys+1)+" Eingabe: "+nr1Eing);
        }
        if (ladrEing != bcSys-1) {
            antwort += "Letzte Adresse falsch!";
            richtig = false;
            adr1.addMsg("Last Adr.:! Korrekt: "+(bcSys-1)+" Eingabe: "+ladrEing);

        }
        if (richtig) {
            antwort="Richtig";
            adr1.addMsg("Korrekt");
        }
        this.lblErgebnis.setText(antwort);
        this.pack();
    }//GEN-LAST:event_onClickAuswertung

    private void jMenuEingabeIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEingabeIpActionPerformed
        // TODO add your handling code here:
        String ip = JOptionPane.showInputDialog("Bitte IP eingeben");
        if (ip == null) {
            return;
        }
        try {
            long zahl = Long.parseLong(ip);
            adr1.setAdresse(zahl);
        } catch (NumberFormatException e) {
            // ist doch keine long, sondern eine Punkt-Notation
            if (ip.indexOf('/') == -1) {
                String maske = JOptionPane.showInputDialog("Bitte Maske eingeben");
                adr1.setzeNeueAdresse(ip, Ipv4Wert.getMaskeToCDIR(maske));
            } else {
                adr1.setzeNeueAdresse(ip);
            }
        }
        this.newAdr(adr1);
    }//GEN-LAST:event_jMenuEingabeIpActionPerformed

    private void jMenuLongtoIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLongtoIpActionPerformed
        // TODO add your handling code here:
        String ip = JOptionPane.showInputDialog("Bitte Zahl eingeben eingeben");
        try {
            long zahl = Long.parseLong(ip);
            JOptionPane.showMessageDialog(null, "Adresse: "+Ipv4Wert.getAdrStr(zahl));
        } catch (NumberFormatException e) {
        }

    }//GEN-LAST:event_jMenuLongtoIpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FensterNetzGrenzen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FensterNetzGrenzen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FensterNetzGrenzen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FensterNetzGrenzen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FensterNetzGrenzen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fld1adr;
    private javax.swing.JTextField fldBC;
    private javax.swing.JTextField fldLadr;
    private javax.swing.JTextField fldNID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEingabeIp;
    private javax.swing.JMenuItem jMenuLongtoIp;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblErgebnis;
    private javax.swing.JLabel lblMaske;
    // End of variables declaration//GEN-END:variables
}

