/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subnetting1;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Moerle
 */
public class FensterZahlensyteme extends javax.swing.JFrame {

    private JLabel[] ergListe;
    private SystByte[] listeByte;

    /**
     * Creates new form FesnterZahlensyteme
     */
    public FensterZahlensyteme() {
        initComponents();
//        this.ergListe = {jLabelErg01, jLabelErg02, jLabelErg03, jLabelErg04, 
//                                jLabelErg05, jLabelErg06, jLabelErg07, jLabelErg08,
//                                jLabelErg09, jLabelErg10, jLabelErg11, jLabelErg12};
        this.ergListe = new JLabel[12];
        this.ergListe[0] = jLabelErg01;
        this.ergListe[1] = jLabelErg02;
        this.ergListe[2] = jLabelErg03;
        this.ergListe[3] = jLabelErg04;
        this.ergListe[4] = jLabelErg05;
        this.ergListe[5] = jLabelErg06;
        this.ergListe[6] = jLabelErg07;
        this.ergListe[7] = jLabelErg08;
        this.ergListe[8] = jLabelErg09;
        this.ergListe[9] = jLabelErg10;
        this.ergListe[10] = jLabelErg11;
        this.ergListe[11] = jLabelErg12;
        listeByte = new SystByte[12];

        this.initListeByte();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTableZahlensyst = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelErg02 = new javax.swing.JLabel();
        jLabelErg03 = new javax.swing.JLabel();
        jLabelErg01 = new javax.swing.JLabel();
        jLabelErg05 = new javax.swing.JLabel();
        jLabelErg04 = new javax.swing.JLabel();
        jLabelErg06 = new javax.swing.JLabel();
        jLabelErg07 = new javax.swing.JLabel();
        jLabelErg08 = new javax.swing.JLabel();
        jLabelErg09 = new javax.swing.JLabel();
        jLabelErg10 = new javax.swing.JLabel();
        jLabelErg11 = new javax.swing.JLabel();
        jLabelErg12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dezimal", "Hexadezimal", "Binär"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTableZahlensyst.setViewportView(jTable1);

        jButton1.setText("Überprüfen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Neu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelErg02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg02.setText("v");

        jLabelErg03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg03.setText("v");

        jLabelErg01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg01.setText("X");

        jLabelErg05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg05.setText("X");

        jLabelErg04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg04.setText("X");

        jLabelErg06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg06.setText("X");

        jLabelErg07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg07.setText("X");

        jLabelErg08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg08.setText("X");

        jLabelErg09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg09.setText("X");

        jLabelErg10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg10.setText("X");

        jLabelErg11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg11.setText("X");

        jLabelErg12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelErg12.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTableZahlensyst, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErg01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg03, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jLabelErg04, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jLabelErg05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErg12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelErg01, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg07, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg08, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg09, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErg11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelErg12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTableZahlensyst, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 
        boolean istFehler;
        SystByte dec, hex, bin;
        for (int zeile = 0; zeile < 12; zeile++) {
            istFehler = false;
            // DEC
            try {
                dec = new SystByte((int) jTable1.getValueAt(zeile, 0));
                if (!listeByte[zeile].equals(dec)) {
                    msg("Zeile " + (zeile + 1) + ", Dezimalwert falsch: " + dec+"/"+listeByte[zeile]);
                    istFehler = true;
                }
                } catch (Exception e) {
                msg("Zeile " + (zeile + 1) + ", Dezimalwert nicht erkannt.");
                istFehler = true;
            }

            // HEX
            try {
                hex = new SystByte((String) jTable1.getValueAt(zeile, 1), 16);
                if (!listeByte[zeile].equals(hex)) {
                    msg("Zeile " + (zeile + 1) + ", Hexadezimalwert falsch: " + hex +"/"+listeByte[zeile]);
                    istFehler = true;
                }
            } catch (Exception e) {
                msg("Zeile " + (zeile + 1) + ", Hexadezimalwert nicht erkannt.");
                istFehler = true;
            }
            // BIN
            try {
                bin = new SystByte((String) jTable1.getValueAt(zeile, 2), 2);
                if (!listeByte[zeile].equals(bin)) {
                    msg("Zeile " + (zeile + 1) + ", Binärwert falsch: " + bin+"/"+listeByte[zeile]);
                    istFehler = true;
                }
            } catch (Exception e) {
                msg("Zeile " + (zeile + 1) + ", Binärwert nicht erkannt.");
                istFehler = true;
            }
            if (istFehler) {
                ergListe[zeile].setText("X, "+listeByte[zeile].getDec());
            } else {
                ergListe[zeile].setText("V");
            }
            this.pack();
            System.out.println("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.initListeByte();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FensterZahlensyteme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FensterZahlensyteme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FensterZahlensyteme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FensterZahlensyteme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FensterZahlensyteme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelErg01;
    private javax.swing.JLabel jLabelErg02;
    private javax.swing.JLabel jLabelErg03;
    private javax.swing.JLabel jLabelErg04;
    private javax.swing.JLabel jLabelErg05;
    private javax.swing.JLabel jLabelErg06;
    private javax.swing.JLabel jLabelErg07;
    private javax.swing.JLabel jLabelErg08;
    private javax.swing.JLabel jLabelErg09;
    private javax.swing.JLabel jLabelErg10;
    private javax.swing.JLabel jLabelErg11;
    private javax.swing.JLabel jLabelErg12;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jTableZahlensyst;
    // End of variables declaration//GEN-END:variables

    private void clearTabelle() {
        for (JLabel feld : ergListe) {
            feld.setText("");
        }
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                jTable1.setValueAt("", i, j);
            }
        }

    }

    public void initListeByte() {
        int spalte;
        for (int i = 0; i < 12; i++) {
            this.listeByte[i] = new SystByte((int) (Math.random() * 256));
        }
        this.clearTabelle();
        for (int i = 0; i < 12; i++) {
            spalte = (int) (Math.random() * 3);
            switch (spalte) {
                case 0:        // Erste Spalte --> Dec
                    this.jTable1.setValueAt(this.listeByte[i].getDec(), i, 0);
                    //this.setCellColor(i, 0, Color.lightGray);
                    break;
                case 1:        // Zweite Spalte --> Hex
                    this.jTable1.setValueAt(this.listeByte[i].getHex(), i, 1);
                    break;
                case 2:        // Dritte Spalte --> Bin
                    //this.jTable1.setValueAt(this.listeByte[i].getDec(), i, 0);
                    this.jTable1.setValueAt(this.listeByte[i].getBin(), i, 2);
                    break;

            }
        }
    }

    void setCellColor(int zeile, int spalte, Color color) {
        TableCellRenderer tableCellRenderer = jTable1.getCellRenderer(zeile, spalte);
        Component c = jTable1.prepareRenderer(tableCellRenderer, zeile, spalte);
        c.setBackground(color);

    }

    private void msg(String eingabe) {
        System.out.println("FensterZahlensysteme: "+eingabe);
    }

}
